version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: DockerfilSe
    ports:
      - "8080:80"
    volumes:
      - ./database:/var/www/html/database
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=exampledb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=exampledb
      # docker compose exec -it postgres psql postgres://postgres:example@postgres:5432/exampledb
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database: